### ISSUE TITLE
vimrc - 'opam config var share' - Unknown option: var

### ISSUE THREAD

**Issue by ianchanning** [ocaml-opam/opam-user-setup#59] opened 2024-02-09 11:41 UTC
After installing the opam setup, via

```sh
$ opam user-setup install
```

when starting nvim, I get the following error:

```
Error detected while processing /home/ian-home/.config/nvim/init.vim[3]../home/ian-home/.vimrc[1064]..function OpamConfOcpIndent:
line    1:
E518: Unknown option: var 
E486: Pattern not found: home
Error detected while processing /home/ian-home/.config/nvim/init.vim[3]../home/ian-home/.vimrc[1064]..function OpamConfMerlin:
line    2:
E518: Unknown option: var 
"~/.vimrc" 1075L, 35019B
```

This is the code that is in my `.vimrc`:

```vim
" ## added by OPAM user-setup for vim / base ## 93ee63e278bdfc07d1139a748ed3fff2 ## you can edit, but keep this line
let s:opam_share_dir = system("opam config var share")
let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')

let s:opam_configuration = {}

function! OpamConfOcpIndent()
  execute "set rtp^=" . s:opam_share_dir . "/ocp-indent/vim"
endfunction
let s:opam_configuration['ocp-indent'] = function('OpamConfOcpIndent')

function! OpamConfOcpIndex()
  execute "set rtp+=" . s:opam_share_dir . "/ocp-index/vim"
endfunction
let s:opam_configuration['ocp-index'] = function('OpamConfOcpIndex')

function! OpamConfMerlin()
  let l:dir = s:opam_share_dir . "/merlin/vim"
  execute "set rtp+=" . l:dir
endfunction
let s:opam_configuration['merlin'] = function('OpamConfMerlin')

let s:opam_packages = ["ocp-indent", "ocp-index", "merlin"]
let s:opam_check_cmdline = ["opam list --installed --short --safe --color=never"] + s:opam_packages
let s:opam_available_tools = split(system(join(s:opam_check_cmdline)))
for tool in s:opam_packages
  " Respect package order (merlin should be after ocp-index)
  if count(s:opam_available_tools, tool) > 0
    call s:opam_configuration[tool]()
  endif
endfor
" ## end of OPAM user-setup addition for vim / base ## keep this line
" ## added by OPAM user-setup for vim / ocp-indent ## 8ddd53b5e3ffc5bc5ef6c0a44f60ae53 ## you can edit, but keep this line
if count(s:opam_available_tools,"ocp-indent") == 0
  source "/home/ian-home/.opam/default/share/ocp-indent/vim/indent/ocaml.vim"
endif
" ## end of OPAM user-setup addition for vim / ocp-indent ## keep this line
```

I tracked the problem down to this line:

```vim
let s:opam_share_dir = system("opam config var share")
```

When you run this in bash
```sh
:!opam config var share
[WARNING] var was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.                                               
/home/ian-home/.opam/default/share
```

Switching to this fixes the problem:
 
```vim
let s:opam_share_dir = system("opam var share")
```

**Comment by kit-ty-kate** [comment] 2024-09-04 15:41
Duplicate of #55 and fixed by #52

**Closed by kit-ty-kate** 2024-09-04 15:41 UTC
